# Generated by Django 4.1.5 on 2023-02-14 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.IntegerField(choices=[(0, 'Standard 301'), (1, 'Standard 501'), (2, 'Standard 701'), (3, 'Cricket'), (4, 'Cricket Cut Throat')], default=1)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('current_sum', models.IntegerField(default=0)),
                ('scores', models.TextField()),
                ('round', models.IntegerField(default=1)),
                ('undo', models.TextField(default='{}')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='game_session', to='user.player')),
            ],
        ),
    ]
