# Generated by Django 4.1.5 on 2023-02-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='round',
        ),
    ]
